### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by permezel** [chdoig/scipy2015-blaze-bokeh#8]
This no longer works.
The s3 data copies are no longer there.

```
Test Notebook
In [1]:  import bokeh
In [2]:  bokeh.__version__
Out[2]: u'1.3.4'
In [3]: import blaze
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-cf28b9f4f41e> in <module>()
----> 1 import blaze

/Users/dap/opt/anaconda3/envs/py27/lib/python2.7/site-packages/blaze/__init__.py in <module>()
      7 
      8 from pandas import DataFrame
----> 9 from odo import odo, convert, append, drop, resource
     10 from odo.backends.csv import CSV
     11 from odo.backends.json import JSON, JSONLines

/Users/dap/opt/anaconda3/envs/py27/lib/python2.7/site-packages/odo/__init__.py in <module>()
     27     from .backends.sas import sas7bdat
     28 with ignoring(ImportError):
---> 29     from .backends.pandas import pd
     30 with ignoring(ImportError):
     31     from .backends.bcolz import bcolz

/Users/dap/opt/anaconda3/envs/py27/lib/python2.7/site-packages/odo/backends/pandas.py in <module>()
    100 
    101 
--> 102 @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
    103 def convert_null_or_nat_to_nat(n, **kwargs):
    104     return pd.NaT

AttributeError: 'module' object has no attribute 'tslib'

```

This is with a python=2.7 env I created.  Does not work with python=3.8 or 3.7.

**Comment by Jebushdd** [comment]
Hi! I'm starting with this project and found the datasets

- the land and ocean lat1 dataset at this link from berkeley library
[http://berkeleyearth.lbl.gov/auto/Global/Gridded/Land_and_Ocean_LatLong1.nc](url)

- the lahman dataset (you have to create an account to be able to download it
[https://data.world/andy/lahmanbaseball](url)
